baseURL = 'https://ferrantedev.com/'
languageCode = 'en-us'
title = 'Lorenzo Ferrante`s tech blog'

theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Lorenzo Ferrante's tech blog"
  defaultColor = "dark" # set default color mode: dark or light
  description = "A blog about software in general. From software product reviews to software development experiments and opinions."

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Lorenzo Ferrante's tech blog"
  name = "Lorenzo Ferrante"
  description = "Welcome! I use this blog to post about software in general. From software product reviews to software development experiments and opinions."

# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/hugo-sid"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/ferrantedev/?locale=en_US"

[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.social"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"